config/routes.rb
Rails.application.routes.draw do
  get 'cart_items/controller'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/products', to: 'products#index'
  # get '/products/:id', to: 'products#show'
  # get '/products/new', to: 'products#new'
  # post '/products', to: 'products#create'
  # get '/products/:id/edit', to: 'products#edit'
  # patch '/products/:id/edit', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'
  root to: 'pages#home'
  resources :products
  resources :posts
  get '/contact', to: 'pages#contact'
  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :product_id, presence: true
  validates :user_id, presence: true
  validates :quantity, presence: true, numericality: true

  def save_or_update_cart_item
    item = self
    # USE THIS IF item=self DOESN'T WORK: cart_item = CartLineItem.find_by(user_id: self.user_id, product_id: self.product_id)
    cart_item = CartLineItem.find_by(user_id: item.user.id, product_id: item.product.id)
    if cart_item.nil?
      item.save
    else
      cart_item.update_attributes(quantity: cart_item.quantity + item.quantity)
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user


  def add_to_basket(amount)
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_line_items
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :stock, presence: true, numericality: true, on: :create
  validates :stock, presence: true, numericality: true, on: :update

  def update_stock(id, quantity)
    # stock of bracelets not packs
    # in controller add stock will pass quantity, decrease stock will pass quanity*-1
    current_product(id)
    current_product.update_attributes(stock: product.stock + quantity)
  end

  def available_product(id)
    current_product(id).stock >= 5
  end

  def current_product(id)
    Product.find_by(id: id)
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def cart
    @cart_items = current_user.cart_items
  end

  def create
    @cart_item = CartLineItem.new(cart_item_params)
    @cart_item.user_id = current_user.id
    @cart_item.save_or_update_cart_item
    redirect_to cart_items_path, notice: 'Added item to cart'
  end

  def destroy
    @cart_item = CartLineItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path, notice: 'Removed item from cart'
  end

  private

  def cart_item_params
    params[:cart_item].permit(:quantity, :product_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all

  end

  def show
    find_post
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to post_path(@post)
  end

  def edit
    find_post
    # @post = Post.find(params[:id])
  end

  def update
    find_post
    # @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    find_post
    # @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:section, :name, :description)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    find_product
    # @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to product_path(@product)
  end

  def edit
    find_product
    # @product = Product.find(params[:id])
  end

  def update
    find_product
    # @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to product_path(@product)
  end

  def destroy
    find_product
    # @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def find_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/about_posts/destroy.html.erb
destroy.html.erb

app/views/about_posts/edit.html.erb
edit.html.erb

app/views/about_posts/index.html.erb
posts#index

app/views/about_posts/new.html.erb
<h3>New Post</h3>
  <%= simple_form_for(@post) do |f| %>
    <%= f.error_notification %>
      <%= f.input :name,
                  required: true
                  # autofocus: true,
                  %>
      <%= f.input :description,
                  required: true,
                  # autofocus: true,
                  as: :text%>
        <%= f.submit %>
  <% end %>

app/views/about_posts/show.html.erb
show.html.erb

app/views/cart_items/controller.html.erb
<h1>CartItems#controller</h1>
<p>Find me in app/views/cart_items/controller.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>GalitForAkim</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/order/confirmation.html.erb
<div class="reel-cont">
  <div class="row d-flex justify-content-center">
    <div class="confirmation col-lg-8 text-center">
      <i class="fas fa-check-circle text-center m-5 checkmark"></i>
      <h3 class="text-center mb-5"> Your booking has been requested. </h3>
      <p class="first text-center"> The owner has 24h to accept the request. You can send him a message and if they agree you can do your payment. Thank you for trusting <span class="nav-brand-small">REC<i class="fas fa-record-vinyl"></i>N<span id="twenty-four">24</span></span>!</p>
      <div class="d-flex justify-content-center mb-3">
          <%= cl_image_tag @booking.location.photos.first.key, class:'d-block w-50 align-items-center' %>
      </div>
      <p> You can view your booking at your <strong><%= link_to "profile", dashboard_path, class: "prof-link" %></strong> page </p>
      <p>Check <strong><%= link_to @booking.location.user.username, profile_path(@booking.location.user) %></strong>  ' s profile page</p>

      <div class="btn-confir d-flex justify-content-center ">
        <button class="btn btn-danger col-md-4 text-center"><%= link_to "Keep Searching", root_path%></button>
      </div>
    </div>
  </div>
</div>

app/views/order/new.html.erb
new.html.erb

app/views/order/show.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-md-3"><%= image_tag @booking.teddy.photos[0]_url, width: '100%' %></div>
    <div class="col">
      <h1>Order #<%= @booking.id %> <small><span class="badge badge-primary"><%= @booking.state %></span></small></h1>
      <ul class="list-unstyled">
        <li><strong>ISSUED ON</strong> <%= @booking.created_at.to_date %></li>
        <li><strong>TEDDY</strong> <%= @booking.teddy.name %> [<%= @booking.teddy_sku %>]</li>
        <li><strong>TOTAL</strong> <%= humanized_money_with_symbol @booking.amount %></li>
        </li>
      </ul>
      <p>Estimated delivery in <strong>2 business days</strong></p>
    </div>
  </div>
</div>

app/views/order/track_your_order.html.erb
track_your_order.html.erb

app/views/order_details/new.html.erb
<%= render 'form' %>

app/views/pages/about.html.erb
about.html.erb

app/views/pages/contact.html.erb
contact.html.erb

app/views/pages/home.html.erb
home.html.erb

app/views/posts/destroy.html.erb
destroy.html.erb

app/views/posts/edit.html.erb
<h3>Edit Post <%= @post.name %> </h3>
  <%= simple_form_for(@post) do |f| %>
    <%= f.input :section %>
    <%= f.input :name %>
    <%= f.input :description,
        required: true,
        # autofocus: true,
        as: :text%>
    <%= f.submit %>

  <% end %>

app/views/posts/index.html.erb
<h1>POSTS</h1>

<p><%= link_to 'New post', new_post_path %></p>

<h2>ABOUT</h2>
<% @posts.where(section: "ABOUT").each do |post| %>
<h3><%= post.id %>. <%= link_to post.name, post_path(post) %></h3>
    <p><%= link_to 'Edit', edit_post_path(post) %></p>
    <p><%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete #{post.name}?"} %></p>
<% end %>

<h2>HOME</h2>
<% @posts.where(section: "HOME").each do |post| %>
<h3><%= post.id %>.
  <%= link_to post.name, post_path(post) %></h3>
    <p><%= link_to 'Edit', edit_post_path(post) %></p>
    <p><%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete #{post.name}?"} %></p>
<% end %>

app/views/posts/new.html.erb
<h3>New Post</h3>
  <%= simple_form_for(@post) do |f| %>
    <%= f.input :section %>
    <%= f.input :name %>
    <%= f.input :description,
        required: true,
        # autofocus: true,
        as: :text%>
    <%= f.submit %>
  <% end %>

app/views/posts/show.html.erb
<h1><%= @post.name %></h1>
  <p><%= link_to 'Back to posts', posts_path %></p>
  <h3> ID #<%= @post.id %> </h3>
  <p><%= @post.description %></p>
  <p><%= link_to 'Edit', edit_post_path(@post.id) %></p>

app/views/products/destroy.html.erb
destroy.html.erb

app/views/products/edit.html.erb
<h3>New product details</h3>
  <%= simple_form_for( @product) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <%= f.input :name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "name" }, as: :string
                  # autofocus: true,
                  %>
      <%= f.input :price,
                  required: true,
                  # autofocus: true,
                  as: :integer%>
       <%= f.input :description,
                  required: true,
                  # autofocus: true,
                  as: :text%>
        <%= f.submit %>
  <% end %>

app/views/products/index.html.erb
<h1>Product List</h1>
  <p><%= link_to 'New product', new_product_path %></p>
  <% @products.each do |product| %>
  <h3><%= link_to product.name, product_path(product) %></h3>
      <p><%= link_to 'Edit', edit_product_path(product) %></p>
      <p><%= link_to 'Delete', product_path(product), method: :delete, data: { confirm: "Are you sure you want to delete #{product.name}?"} %></p>
  <% end %>

app/views/products/new.html.erb
<h3>New product details</h3>
  <%= simple_form_for( @product) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <%= f.input :name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "name" }, as: :string
                  # autofocus: true,
                  %>
      <%= f.input :price,
                  required: true,
                  # autofocus: true,
                  as: :integer%>
       <%= f.input :description,
                  required: true,
                  # autofocus: true,
                  as: :text%>
        <%= f.submit %>
  <% end %>

app/views/products/show.html.erb
<h1>Product page</h1>
  <p><%= link_to 'Back to produc list', products_path %></p>
  <h3><%= @product.name %></h3>
  <p><%= @product.price %></p>
  <p><%= @product.description %></p>

  <%= render './bookings/form' %>

<%= simple_form_for(@product) do |f| %>
      <%= f.input :quantity,
                  required: true,
                  # autofocus: true,
                  as: :integer%>
      <%= f.submit %>
<% end %>